#!/usr/bin/env python3

'''
comp0.py - Educational "compiler" to learn portability
Copyright 2014 Renzo Davoli University of Bologna - Italy
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License a
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
'''

import sys
import codecs
writer = codecs.getwriter('latin-1')
sys.stdout = writer(sys.stdout.buffer)

def main():
	for line in sys.stdin:
		line=line[:-1]
		sys.stdout.write(chr(0))
		if line[:3] == 'IF:':
			sys.stdout.write(chr(1))
			sys.stdout.write(line[3:])
			sys.stdout.write(chr(0))
		elif line == 'ENDIF':
			sys.stdout.write(chr(2))
		elif line[:6] == 'PRINT:':
			for c in line[6:]:
				sys.stdout.write(chr(3))
				sys.stdout.write(c)
				sys.stdout.write(chr(0))
		elif line == 'PRINTIN':
			sys.stdout.write(chr(4))
		elif line[:9] == 'PRINTCHR:':
			sys.stdout.write(chr(5))
			sys.stdout.write('000')
			sys.stdout.write(line[9:])
			sys.stdout.write(chr(0))
		elif line[:5] == 'ERROR':
			sys.stdout.write(chr(6))
		else:
			sys.stderr.write("SYNTAX ERROR\n")
			return 1
		sys.stdout.flush()
	return 0

if __name__=='__main__':
	sys.exit(main())
